/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class game_dlltool_TdxmDllImpl */
#ifndef _Included_game_dlltool_TdxmDllImpl
#define _Included_game_dlltool_TdxmDllImpl
#ifdef __cplusplus
extern "C" {
#endif 
typedef char* (_stdcall *tagencrypt1)(char *,char *);//第一次加密
typedef char* (_stdcall *tagencrypt2)(char *,char *);//第二次加密
 
HINSTANCE m_hmDll;
tagencrypt1 encrypt1;
tagencrypt2 encrypt2;
/*
 * Class:     game_dlltool_TdxmDllImpl
 * Method:    Jstr_encrypt_reversible
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_game_dlltool_TdxmDllImpl_Jstr_1encrypt_1reversible
  (JNIEnv *, jobject, jstring, jstring,jstring);

/*
 * Class:     game_dlltool_TdxmDllImpl
 * Method:    Jstr_encrypt2_reversible
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_game_dlltool_TdxmDllImpl_Jstr_1encrypt2_1reversible
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     game_dlltool_TdxmDllImpl
 * Method:    Jcomm_encrypt_data_Dll
 * Signature: (ILjava/lang/String;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_game_dlltool_TdxmDllImpl_Jcomm_1encrypt_1data_1Dll
  (JNIEnv *, jobject, jint, jstring, jstring, jlong);

/*
 * Class:     game_dlltool_TdxmDllImpl
 * Method:    Jcomm_decrypt_data_Dll
 * Signature: (ILjava/lang/String;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_game_dlltool_TdxmDllImpl_Jcomm_1decrypt_1data_1Dll
  (JNIEnv *, jobject, jint, jstring, jstring, jlong);

/*
 * Class:     game_dlltool_TdxmDllImpl
 * Method:    Jcomm_trailer_value_Dll
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_game_dlltool_TdxmDllImpl_Jcomm_1trailer_1value_1Dll
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     game_dlltool_TdxmDllImpl
 * Method:    JinitDll
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_game_dlltool_TdxmDllImpl_JinitDll
  (JNIEnv *env, jobject);

/*
 * Class:     game_dlltool_TdxmDllImpl
 * Method:    JdistoryDll
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_game_dlltool_TdxmDllImpl_JdistoryDll
  (JNIEnv *env, jobject);

jstring windowsToJstring(JNIEnv* env,char* str);

char* jstringToWindows(JNIEnv* env,jstring jstr);  

#ifdef __cplusplus
}
#endif
#endif
